### ISSUE TITLE
Cross Project Links

### ISSUE THREAD

**Issue by ryanbeard82** [AronGahagan/cpt-dev#8]
The driving path utility does not work on Subproject links.

**Comment by AronGahagan** [comment]
For the line:

```vba
Trace/cptCriticalPath_bas.bas:352:    If tdp.To.UniqueID = t.UniqueID And tdp.From.PercentComplete <> 100 Then
```

Suggest:

```vba
Trace/cptCriticalPath_bas.bas:352:    If tdp.To.Guid = t.Guid And tdp.From.PercentComplete <> 100 Then
```

`t.UniqueID` in a master/sub scenario will return the 'masked' UID and `tdp.To.UniqueID` will return the native UniqueId of the receiver task so they will not match. Also, the `tdp.From.UniqueID` property of the TaskDependency object returns UniqueId of the giver's ghost task in the receiver's Project file, not the Unique Id of the giver task in the giver task's Project. The `tdp.From.Parent` property also returns the receiver's Project file. The only way that I'm aware of to "get at" the giver's native UniqueID and the giver's project, is from the receiver task's `UniqueIdPredecessors` list.

Just a few notes that I thought might help.

**Comment by ryanbeard82** [comment]
There's a field we found a few months ago that stores the actual UID from the corresponding linked file. It's in the same format as the master project UID (calculated using subproject ID).

On my long list of to-dos...probably not happening anytime soon.

**Comment by ryanbeard82** [comment]
Found our old teams chats on the subject:



-ryan

**Comment by AronGahagan** [comment]
I don't remember finding a field, but I do remember that we can start with a [master task UID] and derive its [source task UID] with `[source task UID] = [master task UID] mod 4194304`. We can also get the subproject's `InstertedProjectSummary.UniqueID` using `[inserted project summary UID] = Round([master task UID] / 4194304,0) - 1`.

The problem is that nothing exposes a dependency's [master task UID] (in order to flag it). We have to derive it from the dependency's [source task UID]--but that isn't exposed by the `TaskDependencies`, `PredecessorTasks`, or the `SuccessorTasks` objects. Let's say we have an external giver and an internal receiver. The three aforementioned objects only return the UID of a giver's _ghost task_ which exists in the receiver's subproject (and it does not match the UID in the giver's subproject). The giver's [master task UID] must be derived from the giver's [source task UID], and the only place I can find it is in the `UniqueIDPredecessors` (or `UniqueIDSuccessors`) property.

To get an external task's [master task UID], we need to use: `(([inserted subproject UID]+1) * 4194304) + [source task UID]`.

Either way, I've written a function that takes a Task object and a "p" or "s" variable as inputs and converts either the Task's UniqueIDPredecessors ("p") or UniqueIDSuccessors ("s") into a string of equivalent master project UIDs. Where we would iterate through the TaskDependencies object on a standalone project file before--filtering for only predecessors (`If oLink.To.UID = oTask.UID Then...` or something like that)--we can now iterate over this converted string instead using something like `For Each vLink In Split(strConvertedList,",")`.

```vba
Function cptConvertToMasterUIDs(oTask As Task, strReturn As String) As String
  'strReturn variable expects either "p" for predecessors or "s" for successors
  Dim strProject As String, strList As String, strLinkProject As String, strConvertedList As String
  Dim lngUID As Long, lngLinkUID As Long
  Dim vLink As Variant
  
  If ActiveProject.Subprojects.Count = 0 Then Exit Function
  
  strProject = oTask.Project
  If strReturn = "p" Then
    strList = oTask.UniqueIDPredecessors
  ElseIf strReturn = "s" Then
    strList = oTask.UniqueIDSuccessors
  End If
  For Each vLink In Split(strList, ",")
    If InStr(vLink, "\") > 0 Then 'this should capture both .mpp and server projects
      lngUID = CLng(Mid(vLink, InStrRev(vLink, "\") + 1))   'extract the source task UID
      strLinkProject = Replace(vLink, "\" & lngUID, "")     'strip off the source task UID
      strLinkProject = Replace(strLinkProject, ".mpp", "")  'strip out file extension
      strLinkProject = Mid(strLinkProject, InStrRev(strLinkProject, "\") + 1) 'strip out path or server '<>' thing
      lngLinkUID = ActiveProject.Subprojects(strLinkProject).InsertedProjectSummary.UniqueID + 1 'seed value
    Else
      lngUID = vLink
      lngLinkUID = ActiveProject.Subprojects(strProject).InsertedProjectSummary.UniqueID + 1 'seed value
    End If
    lngLinkUID = (lngLinkUID * 4194304) + lngUID            'derive the master task UID
    strConvertedList = strConvertedList & lngLinkUID & ","  'build the return string
  Next vLink
  strConvertedList = Left(strConvertedList, Len(strConvertedList) - 1) 'strip last comma avoiding null value
  cptConvertToMasterUIDs = strConvertedList
End Function
```
I'll plan to add this, along with a few other related functions, to an upcoming release of `cptCore_bas` just in case you'd like to use it. Just need to polish it up with some error trapping.

**Comment by ryanbeard82** [comment]
Field 4194304 does exactly this. In the context of a master, it gives the master project UID of the real pred task that corresponds to the ghost/external task. Outside of the master project context, it gives the regular project UID. No fancy function necessary, though I appreciate the artistry.

**Comment by ryanbeard82** [comment]
Correction - field id is 185073906

**Comment by AronGahagan** [comment]
...amazing. I did not remember that. So it would be:

`[master task uid] = oTaskDependency.To.GetField(185073906)`
`[source task uid] = oTaskDependency.To.GetField(185073906) Mod 4194304`

**Comment by AronGahagan** [comment]
I'm finding that: 

- For `ExternalTask` dependencies, `oTaskDependency.From.GetField(185073906)  Mod 4194304` = [source task UID] as expected
- For `ExternalTask` dependencies, `oTaskDependency.From.GetField(185073906)` <> [master task UID] (unless I'm missing something). Haven't cracked the code on the returned value, the modulation is sometimes up to 7, and it appears to be influenced by what projects are linked together, but no idea yet.
- For non-ExternalTask dependencies, `oTaskDependency.From.GetField(185073906)` is blank (but we can use `oTaskDependency.From.UniqueID`)

So, in order to get the [master task UID] I still need to use `oTaskDependency.From.Parent` to get at the [inserted project uid] and then use the formula (([inserted project UID] + 1) * 4194304) + [source task UID] to get the [master task UID].

**Comment by ryanbeard82** [comment]
Thank you Aron.

-ryan
